# Generated by Django 5.2.11 on 2026-02-08 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatico')], default='manual', max_length=10)),
                ('contenido', models.CharField(choices=[('database', 'Base de Datos'), ('media', 'Archivos Media'), ('full', 'Completo')], default='full', max_length=10)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
