# Generated by Django 5.2.6 on 2026-02-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('carrera', models.CharField(choices=[('software', 'Desarrollo de Software'), ('animacion_3d', 'Animacion 3D y Efectos Visuales'), ('adsi', 'Analisis y Desarrollo de Sistemas'), ('multimedia', 'Produccion de Multimedia'), ('redes', 'Administracion de Redes'), ('telecomunicaciones', 'Telecomunicaciones'), ('videojuegos', 'Diseno de Videojuegos'), ('ia', 'Inteligencia Artificial'), ('ciberseguridad', 'Ciberseguridad'), ('ciencia_datos', 'Ciencia de Datos'), ('contabilidad', 'Contabilidad y Finanzas'), ('gestion_admin', 'Gestion Administrativa'), ('talento_humano', 'Gestion del Talento Humano'), ('gestion_empresarial', 'Gestion Empresarial'), ('negocios_int', 'Negociacion Internacional'), ('logistica', 'Gestion Logistica'), ('bancaria', 'Gestion Bancaria y Financiera'), ('mercados', 'Gestion de Mercados'), ('comercio_int', 'Comercio Internacional'), ('enfermeria', 'Enfermeria'), ('salud_ocup', 'Salud Ocupacional'), ('farmacia', 'Regencia de Farmacia'), ('primera_infancia', 'Atencion a la Primera Infancia'), ('sst', 'Seguridad y Salud en el Trabajo'), ('nutricion', 'Nutricion y Dietetica'), ('imagenes_dx', 'Imagenes Diagnosticas'), ('electricidad', 'Electricidad Industrial'), ('electronica', 'Electronica'), ('mecanica', 'Mecanica Industrial'), ('automatizacion', 'Automatizacion Industrial'), ('electromecanica', 'Mantenimiento Electromecanico'), ('construccion', 'Construccion'), ('mecatronica', 'Mecatronica'), ('diseno_industrial', 'Diseno Industrial'), ('diseno_grafico', 'Diseno Grafico'), ('audiovisual', 'Produccion Audiovisual'), ('comunicacion', 'Comunicacion Comercial'), ('fotografia', 'Fotografia'), ('modas', 'Diseno de Modas'), ('ambiental', 'Gestion Ambiental'), ('agroindustria', 'Agroindustria Alimentaria'), ('agropecuaria', 'Produccion Agropecuaria'), ('gastronomia', 'Gastronomia'), ('hotelera', 'Gestion Hotelera')], max_length=50)),
                ('autor', models.CharField(max_length=200)),
                ('email_autor', models.EmailField(blank=True, max_length=254)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen de miniatura (o dejar vacio para icono por defecto)')),
                ('enlace_repositorio', models.URLField(blank=True)),
                ('votos', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-votos', '-fecha_publicacion'],
            },
        ),
    ]
