# Generated by Django 5.2.11 on 2026-02-08 17:57

import django.core.validators
import django.db.models.deletion
import repositorio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('categoria', models.CharField(blank=True, help_text='Ej: Lenguaje, Framework, Herramienta, Metodologia', max_length=50)),
            ],
            options={
                'verbose_name': 'Tag / Habilidad',
                'verbose_name_plural': 'Tags / Habilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='proyectogrado',
            options={'ordering': ['-destacado', '-votos', '-fecha_publicacion'], 'verbose_name': 'Proyecto de Grado', 'verbose_name_plural': 'Proyectos de Grado'},
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='anio',
            field=models.PositiveIntegerField(default=2026, help_text='Ano de presentacion', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2035)]),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='descargas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='enlace_demo',
            field=models.URLField(blank=True, help_text='Link demo en vivo'),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revision'), ('publicado', 'Publicado'), ('rechazado', 'Rechazado')], default='borrador', max_length=15),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='ficha',
            field=models.CharField(blank=True, help_text='Numero de ficha SENA', max_length=20),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='herramientas_usadas',
            field=models.CharField(blank=True, help_text='Ej: Python, React, Figma (separado por comas)', max_length=500),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='instructor_avalador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_avalados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='resumen',
            field=models.TextField(blank=True, help_text='Resumen ejecutivo (max 500 chars)'),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Miniatura del proyecto (recomendado: 400x300px)', null=True, upload_to=repositorio.models.thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='version_actual',
            field=models.CharField(choices=[('V1', 'Version 1 (Borrador)'), ('V2', 'Version 2 (Revision)'), ('FINAL', 'Version Final')], default='V1', max_length=5),
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyectogrado',
            name='enlace_repositorio',
            field=models.URLField(blank=True, help_text='Link GitHub/GitLab/externo'),
        ),
        migrations.AlterField(
            model_name='proyectogrado',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (alternativa a thumbnail)'),
        ),
        migrations.CreateModel(
            name='ArchivoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=repositorio.models.proyecto_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'py', 'js', 'html', 'css', 'java', 'cpp', 'c', 'cs', 'ts', 'jsx', 'tsx', 'json', 'xml', 'sql', 'txt', 'md', 'csv', 'zip', 'rar', '7z', 'tar', 'gz', 'jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'bmp', 'mp4', 'avi', 'mov', 'mkv', 'webm', 'mp3', 'wav', 'ogg', 'obj', 'fbx', 'stl', 'gltf', 'glb', 'blend', 'psd', 'ai', 'fig', 'sketch'])])),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('codigo', 'Codigo Fuente'), ('imagen', 'Imagen'), ('video', 'Video'), ('modelo_3d', 'Modelo 3D'), ('presentacion', 'Presentacion'), ('comprimido', 'Archivo Comprimido'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('hash_sha256', models.CharField(blank=True, help_text='Hash de integridad', max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pendiente'), ('clean', 'Limpio'), ('suspicious', 'Sospechoso')], default='pending', max_length=20)),
                ('version_label', models.CharField(choices=[('V1', 'Version 1 (Borrador)'), ('V2', 'Version 2 (Revision)'), ('FINAL', 'Version Final')], default='V1', max_length=5)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='repositorio.proyectogrado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Proyecto',
                'verbose_name_plural': 'Archivos de Proyecto',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas_log', to='repositorio.archivoproyecto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Descarga',
                'verbose_name_plural': 'Registros de Descarga',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='proyectogrado',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='repositorio.taghabilidad'),
        ),
    ]
