# Generated by Django 5.2.11 on 2026-02-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_taghabilidad_alter_proyectogrado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave interna (ej: software)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo de la carrera', max_length=200)),
                ('cluster', models.CharField(choices=[('TICS', 'Tecnologias de la Informacion'), ('ADMIN', 'Ciencias Administrativas'), ('SALUD', 'Salud y Bienestar'), ('INDUSTRIAL', 'Ingenieria e Industria'), ('CREATIVAS', 'Artes y Diseno'), ('AGRO', 'Agroindustria y Ambiente'), ('TURISMO', 'Turismo y Gastronomia')], max_length=20)),
                ('icono', models.CharField(blank=True, default='fa-graduation-cap', help_text='Clase FontAwesome (ej: fa-code)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion breve de la carrera')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['cluster', 'orden', 'nombre'],
            },
        ),
    ]
