# Generated by Django 5.2.11 on 2026-02-08 22:54

from django.db import migrations

# Default icon mapping per cluster
CLUSTER_ICONS = {
    'TICS': 'fa-microchip',
    'ADMIN': 'fa-briefcase',
    'SALUD': 'fa-heart-pulse',
    'INDUSTRIAL': 'fa-gear',
    'CREATIVAS': 'fa-palette',
    'AGRO': 'fa-leaf',
    'TURISMO': 'fa-utensils',
}

# More specific icons for certain careers
CAREER_ICONS = {
    'software': 'fa-code',
    'animacion_3d': 'fa-cube',
    'adsi': 'fa-laptop-code',
    'multimedia': 'fa-photo-film',
    'redes': 'fa-network-wired',
    'telecomunicaciones': 'fa-tower-cell',
    'videojuegos': 'fa-gamepad',
    'ia': 'fa-robot',
    'ciberseguridad': 'fa-shield-halved',
    'ciencia_datos': 'fa-chart-line',
    'contabilidad': 'fa-calculator',
    'gestion_admin': 'fa-clipboard-list',
    'talento_humano': 'fa-people-group',
    'gestion_empresarial': 'fa-building',
    'negocios_int': 'fa-globe',
    'logistica': 'fa-truck-fast',
    'bancaria': 'fa-landmark',
    'mercados': 'fa-chart-pie',
    'comercio_int': 'fa-ship',
    'enfermeria': 'fa-user-nurse',
    'salud_ocup': 'fa-hard-hat',
    'farmacia': 'fa-pills',
    'primera_infancia': 'fa-baby',
    'sst': 'fa-helmet-safety',
    'nutricion': 'fa-apple-whole',
    'imagenes_dx': 'fa-x-ray',
    'electricidad': 'fa-bolt',
    'electronica': 'fa-microchip',
    'mecanica': 'fa-wrench',
    'automatizacion': 'fa-robot',
    'electromecanica': 'fa-gears',
    'construccion': 'fa-helmet-safety',
    'mecatronica': 'fa-cogs',
    'diseno_industrial': 'fa-compass-drafting',
    'diseno_grafico': 'fa-pen-nib',
    'audiovisual': 'fa-video',
    'comunicacion': 'fa-bullhorn',
    'fotografia': 'fa-camera',
    'modas': 'fa-shirt',
    'ambiental': 'fa-seedling',
    'agroindustria': 'fa-wheat-awn',
    'agropecuaria': 'fa-tractor',
    'gastronomia': 'fa-utensils',
    'hotelera': 'fa-hotel',
}


def populate_carreras(apps, schema_editor):
    Carrera = apps.get_model('repositorio', 'Carrera')

    CARRERA_CHOICES = [
        ('software', 'Desarrollo de Software'),
        ('animacion_3d', 'Animacion 3D y Efectos Visuales'),
        ('adsi', 'Analisis y Desarrollo de Sistemas'),
        ('multimedia', 'Produccion de Multimedia'),
        ('redes', 'Administracion de Redes'),
        ('telecomunicaciones', 'Telecomunicaciones'),
        ('videojuegos', 'Diseno de Videojuegos'),
        ('ia', 'Inteligencia Artificial'),
        ('ciberseguridad', 'Ciberseguridad'),
        ('ciencia_datos', 'Ciencia de Datos'),
        ('contabilidad', 'Contabilidad y Finanzas'),
        ('gestion_admin', 'Gestion Administrativa'),
        ('talento_humano', 'Gestion del Talento Humano'),
        ('gestion_empresarial', 'Gestion Empresarial'),
        ('negocios_int', 'Negociacion Internacional'),
        ('logistica', 'Gestion Logistica'),
        ('bancaria', 'Gestion Bancaria y Financiera'),
        ('mercados', 'Gestion de Mercados'),
        ('comercio_int', 'Comercio Internacional'),
        ('enfermeria', 'Enfermeria'),
        ('salud_ocup', 'Salud Ocupacional'),
        ('farmacia', 'Regencia de Farmacia'),
        ('primera_infancia', 'Atencion a la Primera Infancia'),
        ('sst', 'Seguridad y Salud en el Trabajo'),
        ('nutricion', 'Nutricion y Dietetica'),
        ('imagenes_dx', 'Imagenes Diagnosticas'),
        ('electricidad', 'Electricidad Industrial'),
        ('electronica', 'Electronica'),
        ('mecanica', 'Mecanica Industrial'),
        ('automatizacion', 'Automatizacion Industrial'),
        ('electromecanica', 'Mantenimiento Electromecanico'),
        ('construccion', 'Construccion'),
        ('mecatronica', 'Mecatronica'),
        ('diseno_industrial', 'Diseno Industrial'),
        ('diseno_grafico', 'Diseno Grafico'),
        ('audiovisual', 'Produccion Audiovisual'),
        ('comunicacion', 'Comunicacion Comercial'),
        ('fotografia', 'Fotografia'),
        ('modas', 'Diseno de Modas'),
        ('ambiental', 'Gestion Ambiental'),
        ('agroindustria', 'Agroindustria Alimentaria'),
        ('agropecuaria', 'Produccion Agropecuaria'),
        ('gastronomia', 'Gastronomia'),
        ('hotelera', 'Gestion Hotelera'),
    ]

    CARRERA_A_CLUSTER = {
        'software': 'TICS', 'animacion_3d': 'TICS', 'adsi': 'TICS',
        'multimedia': 'TICS', 'redes': 'TICS', 'telecomunicaciones': 'TICS',
        'videojuegos': 'TICS', 'ia': 'TICS', 'ciberseguridad': 'TICS',
        'ciencia_datos': 'TICS',
        'contabilidad': 'ADMIN', 'gestion_admin': 'ADMIN', 'talento_humano': 'ADMIN',
        'gestion_empresarial': 'ADMIN', 'negocios_int': 'ADMIN', 'logistica': 'ADMIN',
        'bancaria': 'ADMIN', 'mercados': 'ADMIN', 'comercio_int': 'ADMIN',
        'enfermeria': 'SALUD', 'salud_ocup': 'SALUD', 'farmacia': 'SALUD',
        'primera_infancia': 'SALUD', 'sst': 'SALUD', 'nutricion': 'SALUD',
        'imagenes_dx': 'SALUD',
        'electricidad': 'INDUSTRIAL', 'electronica': 'INDUSTRIAL', 'mecanica': 'INDUSTRIAL',
        'automatizacion': 'INDUSTRIAL', 'electromecanica': 'INDUSTRIAL',
        'construccion': 'INDUSTRIAL', 'mecatronica': 'INDUSTRIAL',
        'diseno_industrial': 'INDUSTRIAL',
        'diseno_grafico': 'CREATIVAS', 'audiovisual': 'CREATIVAS',
        'comunicacion': 'CREATIVAS', 'fotografia': 'CREATIVAS', 'modas': 'CREATIVAS',
        'ambiental': 'AGRO', 'agroindustria': 'AGRO', 'agropecuaria': 'AGRO',
        'gastronomia': 'TURISMO', 'hotelera': 'TURISMO',
    }

    for i, (clave, nombre) in enumerate(CARRERA_CHOICES):
        cluster = CARRERA_A_CLUSTER.get(clave, 'TICS')
        icono = CAREER_ICONS.get(clave, CLUSTER_ICONS.get(cluster, 'fa-graduation-cap'))
        Carrera.objects.create(
            clave=clave,
            nombre=nombre,
            cluster=cluster,
            icono=icono,
            orden=i,
            activa=True,
        )


def reverse_populate(apps, schema_editor):
    Carrera = apps.get_model('repositorio', 'Carrera')
    Carrera.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_carrera'),
    ]

    operations = [
        migrations.RunPython(populate_carreras, reverse_populate),
    ]
