# Generated by Django 5.2.6 on 2026-02-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
        ('asignaciones', '0001_initial'),
        ('instructores', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proyecto', 'aprendiz'), name='unique_active_assignment_per_project'),
        ),
    ]
