# Generated by Django 5.2.6 on 2026-02-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], max_length=50),
        ),
    ]
